import type { Metadata } from "next";
import { Press_Start_2P, Pixelify_Sans, Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "./sections/NavBar";
import Footer from "./sections/Footer";

const pressStart2P = Press_Start_2P({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-main",
});

const pixelifySans = Pixelify_Sans({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-headline",
});

const monsterrat = Montserrat({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="antialiased">
      <body
        className={`${pressStart2P.variable} ${monsterrat.variable} ${pixelifySans.variable} flex min-h-screen flex-col overflow-x-hidden`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
