import type { Metadata } from "next";
import { Press_Start_2P, Saira_Stencil_One } from "next/font/google";
import "./globals.css";
import NavBar from "./sections/NavBar";

const pressStart2P = Press_Start_2P({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-main",
});

const sairaStencilOne = Saira_Stencil_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body
        className={`${pressStart2P.variable} ${sairaStencilOne.variable} flex min-h-full flex-col`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
